version: "3"
services:
  fastpages:
    working_dir: /data
    environment:
        - INPUT_BOOL_SAVE_MARKDOWN=false
    build:
      context: ../_action_files
      dockerfile: ./Dockerfile
    container_name: fastpages-dev
    image: fastpages-dev
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    volumes:
      - ../:/data/
    command: /fastpages/action_entrypoint.sh